# Generated by Django 4.2.4 on 2024-01-02 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes_staticfiles', '0002_remove_phase2question_response_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phase1question',
            options={'verbose_name_plural': 'Phase 1 Questions'},
        ),
        migrations.AlterModelOptions(
            name='phase2question',
            options={'verbose_name_plural': 'Phase 2 Questions'},
        ),
        migrations.AlterModelOptions(
            name='phase3question',
            options={'verbose_name_plural': 'Phase 3 Questions'},
        ),
        migrations.AlterModelOptions(
            name='phase3quiz',
            options={'verbose_name_plural': 'Phase 3 Quizzes'},
        ),
    ]
